Algorithm = App.class Pane.class Interface.class Menu.class Controller.class DynamicController.class Grid.class Sueue.class Pseudocode.class DrawableStack.class ElementClearer.class Element.class 

CLASSES = Main.class $(addprefix Algorithm/, $(Algorithm))

### ALL ###

ALL: $(CLASSES) 

Main.class: Main.java
	javac Main.java

### ALGORITHM ###

Algorithm/App.class: Algorithm/App.java
	javac Algorithm/App.java

Algorithm/Pane.class: Algorithm/Pane.java
	javac Algorithm/Pane.java

Algorithm/Interface.class: Algorithm/Interface.java
	javac Algorithm/Interface.java

Algorithm/Menu.class: Algorithm/Menu.java
	javac Algorithm/Menu.java

Algorithm/Controller.class: Algorithm/Controller.java
	javac Algorithm/Controller.java

Algorithm/DynamicController.class: Algorithm/DynamicController.java
	javac Algorithm/DynamicController.java

Algorithm/Grid.class: Algorithm/Grid.java
	javac Algorithm/Grid.java

Algorithm/Sueue.class: Algorithm/Sueue.java
	javac Algorithm/Sueue.java

Algorithm/Pseudocode.class: Algorithm/Pseudocode.java
	javac Algorithm/Pseudocode.java

Algorithm/DrawableStack.class: Algorithm/DrawableStack.java
	javac Algorithm/DrawableStack.java

Algorithm/ElementClearer.class: Algorithm/ElementClearer.java
	javac Algorithm/ElementClearer.java

Algorithm/Element.class: Algorithm/Element.java
	javac Algorithm/Element.java

clean:
	rm -rf ./Main.class
	rm -rf ./Algorithm/*.class
